language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install sonar:sonar
addons:
  sonarcloud:
    organization: "erudika"
    token:
      secure: "HU11SwQ8NqCxvn0xkkOKDlGJwVkKM4Cwf13DMjq+1q7V5QK3+rQXf8kbawBIMLr7L8rkmOYSxUCKg94PRTbrxBFRvaLZsuZhgOAte3gB2DNNGd2FCiT6GuXnzYJRkYXZe4V0SsXC0TQJKAHw3RhZSkBUgmVmojR9Q4SjPcTSfU2bGDenURtr+0B87FJptl+K1pKvl6vVXNLpMYGf3Kr1IokPrB8coCSWL98klN4G7+2u+raFiFs1FbWB/334iwVs+LoGr+fVVRw2kz4Tk5jH4NAWjQLXTuYMTc0hH9cI8Gx6PNoMUtQlWttyrzBsGLULzrso0f4eujHaHkL5h9tLD9B39cSn2I7lwoAeg5BG7AZ0xs6XUSr1G+wyJzHkkjPYZczlntQUY6w/nxNFq6O7lw9dvsxwY+Uh7gtdS3UWF/cz2Bs1bL9eg0FV5lYU9WnwyBR0nkCtffwAwhMEfE/aMSKjJHUKMpERyusyy8voOFWl8oDSUN1ZaGfRx3hyJoRKzDTLChMyYJ6Hoym1f/y9t1IO2UL/PynuMqaphbzBCBM49aSNqRDLNRM/94LzSj5kcwDQ6LfA54QM9AhsmNMHAW83F78gFVCCxwUw3zqOKiH7z7UYASHNLLcKOHmOv0nqy51zPMN/nh7+SUfY6iiMNVY/iHs383Iob2cDpOJ8n5o="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never
    
